export const CONFIG = {
    API_BASE: 'https://mail.chatgpt.org.uk/api',
    DEFAULT_API_KEY: 'gpt-test',
    STORAGE_KEYS: {
        API_KEY: 'gptmail_api_key',
        MAIL_PROVIDER_ID: 'aifengyue_mail_provider_id',
        MAIL_PROVIDER_API_KEYS: 'aifengyue_mail_provider_api_keys',
        MAIL_PROVIDER_USAGE_SNAPSHOTS: 'aifengyue_mail_provider_usage_snapshots',
        CURRENT_EMAIL: 'current_temp_email',
        GENERATED_PASSWORD: 'generated_password',
        GENERATED_USERNAME: 'generated_username',
        REGISTRATION_START_TIME: 'registration_start_time',
        LOG_DEBUG_ENABLED: 'aifengyue_log_debug_enabled',
        RUNTIME_LOG_BUFFER: 'aifengyue_runtime_log_buffer',
        AUTO_RELOAD_ENABLED: 'aifengyue_auto_reload_enabled',
        CHAT_MESSAGES_TIMEOUT_SECONDS: 'aifengyue_chat_messages_timeout_seconds',
        ACCOUNT_POINT_POLL_SECONDS: 'aifengyue_account_point_poll_seconds',
        TOKEN_POOL_ENTRIES: 'aifengyue_token_pool_entries',
        TOKEN_POOL_CHECK_SECONDS: 'aifengyue_token_pool_check_seconds',
        TOKEN_POOL_LOCK: 'aifengyue_token_pool_lock',
        TOKEN_POOL_SUMMARY: 'aifengyue_token_pool_summary',
        TOKEN_POOL_LAST_CHECK_AT: 'aifengyue_token_pool_last_check_at',
        TOKEN_POOL_NEXT_ALLOWED_AT: 'aifengyue_token_pool_next_allowed_at',
        TOKEN_POOL_BACKOFF_LEVEL: 'aifengyue_token_pool_backoff_level',
        TOKEN_POOL_LAST_ERROR: 'aifengyue_token_pool_last_error',
        MODEL_SORT_ENABLED: 'aifengyue_model_sort_enabled',
        MODEL_FAMILY_CUSTOM_RULES: 'aifengyue_model_family_custom_rules',
        MODEL_POPUP_SORT_METRIC: 'aifengyue_model_popup_sort_metric',
        MODEL_POPUP_SORT_DIRECTION: 'aifengyue_model_popup_sort_direction',
        SIDEBAR_LAYOUT_MODE: 'aifengyue_sidebar_layout_mode',
        SIDEBAR_THEME: 'aifengyue_sidebar_theme',
        SIDEBAR_DEFAULT_TAB: 'aifengyue_sidebar_default_tab',
        SIDEBAR_DEFAULT_OPEN: 'aifengyue_sidebar_default_open',
    },
    API_QUOTA_LIMIT: 1000,
    VERIFICATION_CODE_PATTERNS: [
        /验证码[：:]\s*(\d{4,8})/,
        /code[：:]\s*(\d{4,8})/i,
        /(\d{4,8})\s*(?:是|为)?(?:您的)?验证码/,
        /Your (?:verification )?code is[：:\s]*(\d{4,8})/i,
        /完成注册[：:]\s*(\d{4,8})/,
        /registration[：:\s]*(\d{4,8})/i,
    ],
};

export const SIDEBAR_INITIAL_STATE = {
    email: '',
    username: '',
    password: '',
    status: 'idle',
    statusMessage: '等待操作...',
    pollCount: 0,
    verificationCode: '',
};
